### ISSUE TITLE
BUG InvalidOperationException When the returned field is not nullable

### ISSUE THREAD

**Issue by vipwan** [itsoli91/OpenApiToRefit#1]

**Comment by vipwan** [comment]
`InvalidOperationException: The ignore condition 'JsonIgnoreCondition.WhenWritingNull' is not valid on value-type member 'Code' on type 'MT.AppGetCommonsEndpointResponse'. Consider using 'JsonIgnoreCondition.WhenWritingDefault'.`


when returned field is not nullable , The generated DTO should not require `JsonIgnoreAttribute`

![image](https://user-images.githubusercontent.com/13956765/193064139-0cfa3fa1-c3a5-44b7-8203-8c3e3ff2c17d.png)
Here should remove `JsonIgnoreAttribute `or just set JsonIgnoreAttribute.Condition = `WhenWritingDefault`

**Comment by vipwan** [comment]
In addition, whether it is possible to put the namespace of public references in a separate template 
eg, 
System.Text.Json.Serialization,
System.Threading.Tasks,
System.Collections.Generic,
System.Threading.Tasks, 
Because the generated code is a bit bloated

**Comment by itsoli91** [comment]
Thank you for reporting, I published a new nuget version.
Please check, and let me know if your problem is solved.
