### ISSUE TITLE
Add options to return IApiResponse

### ISSUE THREAD

**Issue by vulovicv23** [itsoli91/OpenApiToRefit#2]
Ive been using your tool for some time now and the only thing im missing from it is the option to choose to return IApiResponse instead of T. Can this be made?

Thanks man, really appreciate this!

**Comment by itsoli91** [comment]
Hi,
Sorry I was on vacation, I will check it and fix it soon.

**Comment by itsoli91** [comment]
@vulovicv23 it is added now, you can check it out
